<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Customer "Remember Me" template
 */

/** @var \Magento\Persistent\Block\Form\Remember $block */

?>
<div id="remember-me-box" class="field choice persistent">
    <?php $rememberMeId = 'remember_me' . $block->getRandomString(10); ?>
    <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?= $block->escapeHtmlAttr($rememberMeId) ?>" <?php if ($block->isRememberMeChecked()) : ?> checked="checked" <?php endif; ?> title="<?= $block->escapeHtmlAttr(__('Remember Me')) ?>" />
    <span></span>
    <label for="<?= $block->escapeHtmlAttr($rememberMeId) ?>" class="label"><span class="form-create-account__remember"><?= $block->escapeHtml(__('Remember Me')) ?></span><a class="form-create-account__link-tip js-hook__link-tip" href="#"><?= $block->escapeHtml(__("What's this?")) ?></a></label>
</div>


<div class="window-overlay js-hook__window-overlay" style="display: none;"></div>
<div id="remember-me-popup" class="remember-me-popup" style="display: none;">
    <div class="remember-me-popup__head">
        <h3 class="remember-me-popup__title"><?= $block->escapeHtml( __( "What's this?" ) ) ?></h3>
        <a href="#" class="js-hook__remember-me-popup-close remember-me-popup__close" title="Close"><?= $block->escapeHtml( __( 'Close' ) ) ?></a>
    </div>
    <div class="remember-me-popup__body">
        <p><?= $block->escapeHtml( __( 'Checking "Remember Me" will let you access your shopping cart on this computer when you are logged out' ) ) ?></p>
        <div class="remember-me-popup-close-button a-right">
            <a href="#" class="js-hook__remember-me-popup-close remember-me-popup__button" title="Close"><span><?= $block->escapeHtml( __( 'Close' ) ) ?></span></a>
        </div>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        function toggleRememberMepopup(event){
            $('#remember-me-popup').toggle('easing');
            $('.js-hook__window-overlay').toggle();
            return false;
        }

        $('.js-hook__remember-me-popup-close').on('click', toggleRememberMepopup);
        $('.js-hook__link-tip').on('click', toggleRememberMepopup);
    });
</script>